const express = require('express')
const router = express.Router()
const homepageController = require('../controllers/homepageController')
const productController = require('../controllers/productController')
const aboutController = require('../controllers/aboutController')
const contactController = require('../controllers/contactController')
const categoryController = require('../controllers/categoryController')
const loginController = require('../controllers/loginController')
const signupController = require('../controllers/signupController')
const forgetController = require('../controllers/forgetController')
const searchController = require('../controllers/searchController')
const { body } = require('express-validator')
const dashboardController = require('../controllers/dashboardController')
const logoutController = require('../controllers/logoutController')
const { isLoggedIn, isNotLoggedIn } = require('../helpers/auth')
const mailController = require('../controllers/mailController')
const resetController = require('../controllers/resetController')
const AdminProductController = require('../controllers/AdminProductController')
const upload = require('../helpers/upload')
const resize = require('../helpers/resize')

router.get('/', homepageController)
router.get('/product/:id', productController)
router.get('/category/:id', categoryController)
router.get('/about', aboutController)
router.get('/contact', contactController)
router.get('/search', searchController)
router.get('/dashboard', dashboardController)

router.get('/login', isNotLoggedIn, loginController.get)
router.post('/login', isNotLoggedIn, body('password').isLength({ min: 6 }), loginController.post)
router.get('/signup', isNotLoggedIn, signupController.get)
router.post('/signup', isNotLoggedIn, body('name').notEmpty(), body('password').isLength({ min: 6 }), signupController.post)
router.get('/forget', isNotLoggedIn, forgetController.get)
router.post('/forget', isNotLoggedIn, body('email').isEmail().normalizeEmail().toLowerCase(), forgetController.post)
router.get('/logout', logoutController)
router.get('/mail', mailController)
router.get('/reset', resetController.get)
router.post('/reset', isNotLoggedIn, body('password').isLength({ min: 6 }), resetController.post)
router.get('/admin/create', AdminProductController.get)
router.post('/admin/create', upload.single('image'), resize, AdminProductController.post)

module.exports = router
